In [1]:
? cat # help 

search: cat catch catch_backtrace vcat hcat hvcat hvncat CartesianIndex



```
cat(A...; dims)
```

Concatenate the input arrays along the specified dimensions in the iterable `dims`. For dimensions not in `dims`, all input arrays should have the same size, which will also be the size of the output array along that dimension. For dimensions in `dims`, the size of the output array is the sum of the sizes of the input arrays along that dimension. If `dims` is a single number, the different arrays are tightly stacked along that dimension. If `dims` is an iterable containing several dimensions, this allows one to construct block diagonal matrices and their higher-dimensional analogues by simultaneously increasing several dimensions for every new input array and putting zero blocks elsewhere. For example, `cat(matrices...; dims=(1,2))` builds a block diagonal matrix, i.e. a block matrix with `matrices[1]`, `matrices[2]`, ... as diagonal blocks and matching zero blocks away from the diagonal.

See also [`hcat`](@ref), [`vcat`](@ref), [`hvcat`](@ref), [`repeat`](@ref).

# Examples

```jldoctest
julia> cat([1 2; 3 4], [pi, pi], fill(10, 2,3,1); dims=2)
2×6×1 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.14159  10.0  10.0  10.0
 3.0  4.0  3.14159  10.0  10.0  10.0

julia> cat(true, trues(2,2), trues(4)', dims=(1,2))
4×7 Matrix{Bool}:
 1  0  0  0  0  0  0
 0  1  1  0  0  0  0
 0  1  1  0  0  0  0
 0  0  0  1  1  1  1
```


## Varialbles

In [2]:
x=10
x+1

11

In [3]:
"Hello Julia" # string in double code

"Hello Julia"

In [4]:
'h' # single code just for charecter

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [5]:
δ = 0.00001 #unicode names 

1.0e-5

In [6]:
pi #inbuilt pi value 

π = 3.1415926535897...

In [7]:
sqrt(10) #square root

3.1622776601683795

In [8]:
sqrt=19 # if we assign some value to in built function it will throw an error

LoadError: cannot assign a value to variable Base.sqrt from module Main

In [9]:
vector=[1,2,3,4] #array/ vector is  treated as column vector by default

4-element Vector{Int64}:
 1
 2
 3
 4

In [10]:
vector_h=[1 2 3 4] # spaces - horizontall concatination

1×4 Matrix{Int64}:
 1  2  3  4

In [11]:
vector_v=[1;2; 3; 4] # semi colen- vertical concatination

4-element Vector{Int64}:
 1
 2
 3
 4

In [12]:
arr = [[1 2 3 ];[4 5 6]] # verticall concatination of array

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [13]:
vector[1] #slicing

1

In [14]:
vector[2:end] # end keyword means till end of the array

3-element Vector{Int64}:
 2
 3
 4

In [15]:
vector[-1] # negative numbers don't work 

LoadError: BoundsError: attempt to access 4-element Vector{Int64} at index [-1]

In [16]:
vector[2:end-1] # but we can use end keyword with negative number

2-element Vector{Int64}:
 2
 3

In [17]:
arr[:] # column major flip all the oder of indexs 

6-element Vector{Int64}:
 1
 4
 2
 5
 3
 6

In [18]:
arr' #transpose

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

- Performing Addition and Multiplication with each element of array.
- println() function prints next statement in next line.

In [19]:
println("Addition in array",arr.+1) 
print("Multiplication in array",arr.*2)

Addition in array[2 3 4; 5 6 7]
Multiplication in array[2 4 6; 8 10 12]

In [20]:
log.(arr) #log of every element

2×3 Matrix{Float64}:
 0.0      0.693147  1.09861
 1.38629  1.60944   1.79176

In [21]:
arr

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [22]:
arr\ [5,6] # matrix opretionsx

3-element Vector{Float64}:
 -2.055555555555553
  0.1111111111111107
  2.2777777777777763

- Slove Ax=b
- where A = arr, b=[5,6]

In [23]:
A= arr
b= [5,6]
x=A \ b # it multiplies A inverse for the left 
x

3-element Vector{Float64}:
 -2.055555555555553
  0.1111111111111107
  2.2777777777777763

In [24]:
A*x == b

false

## Data type

In [25]:
typeof(A) # It shows the data type and the element type 

Matrix{Int64} (alias for Array{Int64, 2})

In [26]:
typeof(arr)

Matrix{Int64} (alias for Array{Int64, 2})

In [27]:
size(arr)  # Size of array

(2, 3)

In [29]:
eltype(arr) # element type

Int64

In [30]:
[1, 3, 5.4, -2 ] #number of elements in array, it's Data Type and element type

4-element Vector{Float64}:
  1.0
  3.0
  5.4
 -2.0

- Number of elements is 4
- Data Type is Vector
- Element type is "Complex" because of "Complex" element type present.

In [31]:
[1,3,4.6, 3+2im] #number of elements in array, it's Data Type and element type

4-element Vector{ComplexF64}:
 1.0 + 0.0im
 3.0 + 0.0im
 4.6 + 0.0im
 3.0 + 2.0im

- Number of elements is 5
- Data Type is Vector
- Element type is "Any" because of mixed element type present.

In [32]:
[1,3,4.6, "Foo", 'f']

5-element Vector{Any}:
 1
 3
 4.6
  "Foo"
  'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)

## Dictonary
- It gives Data Type i.e dictonary.
- Data type of key and value.
- Number of entries in it.

In [36]:
d = Dict('a' => 1, 'b' => 2, 'c' => 3)

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [37]:
keys(d)

KeySet for a Dict{Char, Int64} with 3 entries. Keys:
  'a'
  'c'
  'b'

In [38]:
values(d)

ValueIterator for a Dict{Char, Int64} with 3 entries. Values:
  1
  3
  2

In [41]:
merge!(d, Dict('e' => 4)) # Adding key and value in dictonary

Dict{Char, Int64} with 4 entries:
  'a' => 1
  'c' => 3
  'e' => 4
  'b' => 2

In [46]:
s= Set([1, 2, 3, 4, 5]) #set

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [47]:
 4 in s # in operator

true

## Tuples

In [51]:
(1, 3, 2.3, 5) 

(1, 3, 2.3, 5)

In [49]:
typeof((1, 3, 2.3, 5)) 

Tuple{Int64, Int64, Float64, Int64}

In [52]:
h , g = (1,3), (4,5)

((1, 3), (4, 5))

In [55]:
(h..., g...) #tuple concatination

(1, 3, 4, 5)

In [ ]:
#30:45